server:
  port: 1028

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://118.25.1.246:8761/eureka/
  healthcheck:
    enabled: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: springcloud_hbase

  redis:
    database: 0
    host: 192.168.1.26
    port: 6379
    password: Aroot234
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000